LIBS-565 - Update to Java 11
avides/xpath-utils pull request #1
Opened 2019-11-13 13:01 UTC by hennes-maertins

* Update to Java 11
* Add GitHub actions
* Remove Jenkins and Travis

2019-11-13 14:53 UTC, julian-eggers requested changes

2019-11-13 14:53 UTC, julian-eggers commented on pom.xml
> +    <github-release-plugin.version>1.2.0</github-release-plugin.version>
1.4.0

2019-11-13 14:53 UTC, julian-eggers commented on pom.xml
> +    <maven-surefire-plugin.version>2.22.1</maven-surefire-plugin.version>
2.22.2

2019-11-13 14:53 UTC, julian-eggers commented on pom.xml
> +    <maven-failsafe-plugin.version>2.22.1</maven-failsafe-plugin.version>
2.22.2

2019-11-13 15:04 UTC, julian-eggers submitted a review, later dismissed

2019-11-13 15:51 UTC, julian-eggers approved these changes

2019-11-14 08:00 UTC, mrhnrk approved these changes

2019-11-14 08:01 UTC, merged